### ISSUE TITLE
Users should have option to select multiple plant and fish types

### ISSUE THREAD

**Issue by jessicaday** [baliga-lab/pf1010-web#109]
Users must have the ability to select multiple plant types and multiple fish types for their system. If their type of plant/fish isn't already in the system, they should have the option to type in the type of plant/fish they're using and it should send us a notification to let us know they've entered a new type of plant/fish that didn't exist before (in case it actually does exist and we need them to change it).

THIS IS PRIORITY #2

**Comment by weiju** [comment]
After looking into this, our data model supports multiple fish and plants per system no problem, but we essentially have still these issues:

1. There is no "edit" form, just create (which is issue #108). So a lot hangs on creating that edit form
2. we have a curious dependency on Angular 1. I understand one would add such dependency for conveniences in form handling, but Angular 1 been considered a dead end by many for 2-3 years now and has been superseded by other technology. My suggestion is to eliminate the Angular dependency, it seems to be limited to form entry, which means system data and measurements which we have to modify in large part anyways.
3. user defined fish and plants are still an open issue because it opens a hole for vandalism. I am willing to give it a try and see what we can do here

**Comment by weiju** [comment]
now we have the possibility to create systems with multiple fish and plants. I have tested this on Chrome and Firefox. Point 2 is also resolved for the create form, no dependency to Angular 1 anymore.

**Comment by weiju** [comment]
I've added the possibility for systems to change the plant and fish types, to do this, you go to the Edit page, by clicking on the pencil icon next to the system's home page.

**Comment by weiju** [comment]
separated user-defined plant and fish types to #115, so we can now close this issue
