### ISSUE TITLE
Pre-established vs established system default on analysis page

### ISSUE THREAD

**Issue by jessicaday** [baliga-lab/pf1010-web#111]
When users first enter the analysis page, the default for viewing data should be "all systems". If users scroll over the word "pre-established only" or "established only" on the drop down menu, it should pop up a text box explaining what each of those things mean. Users can choose to filter their data results using that, but the default screen should always show all of the data.

THIS IS PRIORITY #1

**Comment by weiju** [comment]
I've now added the "all systems" option for general analytics and it's already deployed in production right now. Now, there are actually 2 analysis pages that have this feature, and the other one is when a user analyzes an individual system instead of coming from the Explore page. Should we add that option there, too or does that not make sense ?

2. Could you please provide a help text for the pre-established and established options, not sure if I can accurately describe that.

**Comment by jessicaday** [comment]
Thank you! 

1. I think eventually we will need this ability even on the page where you analyze an individual system, because we will need to add another function allowing people to select other systems to analyze on that page. In that case, they should be able to select what type of system they want to view. However, if they only have 1 system in the analysis page, they shouldn't have the option to select pre vs established systems. 

2. Yes, I can provide a help text, but I can't remember the exact data we added into the algorithm. Can you check on the back end and see what if "if, then" statements say? Then I can verbally explain how that works on the website.

**Comment by weiju** [comment]
about 1. well, in that case we could simply drop the status filter for the single system view (for now), because
there is no way to add another system in that view ?

**Comment by weiju** [comment]
Hm, I've had to make 15 releases in the past 3 days to remove the redundancy in the graph code, one of the problems was that there were 2 700+ line Javascript modules that handled analysis for a single system or a multi-system comparison. Put the common code into a separate module and only kept the differences separate so now not every change on those files will increase the technical debt. There is still that glaring architecture problem that values are filtered on the client instead of just delegating it to the database layer.

**Comment by weiju** [comment]
Now the user system analysis has the "all" status selected by default, too.
