### ISSUE TITLE
Explore Tab - Missing default data

### ISSUE THREAD

**Issue by jessicaday** [baliga-lab/pf1010-web#91]
Should be able to see ALL systems (leaves) as default on “explore” tab - pre-established, established, etc. Wei-ju will work on this. @weiju

**Comment by weiju** [comment]
actually the system is retrieving all systems, but they do not get rendered for some reason, for now I assume it is something with the timing of initialization between Google Maps API and the application.

**Comment by weiju** [comment]
ok,  found the filter, need to see what it actually does, I placed the aqxmap.js functions in their own namespace,  need to do this with all our Javascript files,  since the large amount of global names will inevitably lead to problems sooner or later. Also, there were a couple of issues that could have been caught by running the source through JsLint.
